-- Database: GLOBALNEW Metadata version: 2 Exported: Dec 8, 2022
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_6979_BI_REPORTS" USING 'GCG_6979_BI_REPORTS.mkd' PAGESIZE=4096 (
 "BI_RUN_ID" NUMERIC(8,0),
 "EMPL" CHAR(6),
 "MONTH_0" NUMERIC(9,2),
 "MONTH_1" NUMERIC(9,2),
 "MONTH_2" NUMERIC(9,2),
 "MONTH_3" NUMERIC(9,2),
 "MONTH_4" NUMERIC(9,2),
 "MONTH_5" NUMERIC(9,2),
 "MONTH_6" NUMERIC(9,2),
 "MONTH_7" NUMERIC(9,2),
 "MONTH_8" NUMERIC(9,2),
 "MONTH_9" NUMERIC(9,2),
 "MONTH_10" NUMERIC(9,2),
 "MONTH_11" NUMERIC(9,2),
 "YEAR_0" NUMERIC(9,2),
 "YEAR_1" NUMERIC(9,2),
 "YEAR_2" NUMERIC(9,2) );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
